# Generated by Django 3.2.10 on 2021-12-31 16:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('values', models.TextField(blank=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
